version: 2
jobs:
  lint:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:10.15.3 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: npx eslint src/feature1.js # run the `echo` command
  test:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run: npm install && npm test
  deploy:
    docker:
      - image:  circleci/node:10.15.3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Deploy to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  workflow1:
    jobs:
      - lint
      - test:
          requires:
            - lint
      - deploy:
          requires:
            - test
